const resObj = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "342192",
      name: "Khan Biryani Center",
      uuid: "4d385942-5d1b-4b37-9c3e-1b9ece4a701d",
      city: "10459",
      area: "Sector 62",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "dn01p3cekdqmymcfej5f",
      cuisines: ["Biryani", "Mughlai"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: "39 MINS",
      lastMileTravel: 5,
      slugs: {
        restaurant: "khan-biryani-center-sector-64-sector-64",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "RN-40, RASULPUR NAVADA, B-BLOCK, SECTOR-62, NOIDA,  Gautam Buddha Nagar , UttarPradesh-201309",
      locality: "B Block",
      parentId: 117157,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 5100,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5100,
        message: "",
        title: "Delivery Charge",
        amount: "5100",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7204533~p=22~eid=00000188-fbc1-5bd6-14c5-66eb00981605~srvts=1687850933206",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "342192",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.8",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "681292",
      name: "GLOBO Ice Creams Of The World",
      uuid: "ae5f7fe3-d236-48dd-be79-2ba21c6176ce",
      city: "10459",
      area: "Ghaziabad",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "6a6aa5b55c2494fe25380dcd71dd54b9",
      cuisines: ["Ice Cream", "Desserts", "Bakery"],
      tags: [],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 15,
      minDeliveryTime: 10,
      maxDeliveryTime: 20,
      slaString: "10-20 MINS",
      lastMileTravel: 1.899999976158142,
      slugs: {
        restaurant: "globo-ice-creams-of-the-world-new-indirapuram-indirapuram",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "PLOT NO. CS-3, Upper Ground Back Side, C.S-4, Sucheta Kriplani Marg, U.G.F, Gyan Khand II, Indirapuram, Ghaziabad, Uttar Pradesh 201014",
      locality: "Indirapuram",
      parentId: 22303,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        subHeader: "UPTO ₹80",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "681292",
        deliveryTime: 15,
        minDeliveryTime: 10,
        maxDeliveryTime: 20,
        lastMileTravel: 1.899999976158142,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "380599",
      name: "BOX8 - Desi Meals",
      uuid: "4f20dfc1-1dcc-4353-ba37-54f4a752a484",
      city: "10459",
      area: "Ghaziabad",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "2c36db5027b5abe00ccc15bf455ea70b",
      cuisines: ["North Indian", "Biryani", "Thalis", "Home Food"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 18,
      minDeliveryTime: 13,
      maxDeliveryTime: 23,
      slaString: "13-23 MINS",
      lastMileTravel: 1.899999976158142,
      slugs: {
        restaurant: "box8-desi-meals-gyan-khand-ii-indirapuram",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "PLOT NO. CS-3, Upper Ground Back Side, C.S-4, Sucheta Kriplani Marg, U.G.F, Gyan Khand II, Indirapuram, Ghaziabad, Uttar Pradesh 201014",
      locality: "Indirapuram",
      parentId: 10655,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "380599",
        deliveryTime: 18,
        minDeliveryTime: 13,
        maxDeliveryTime: 23,
        lastMileTravel: 1.899999976158142,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "718086",
      name: "24Seven",
      uuid: "e6b92f1d-c524-4170-a784-9ed8c1a813d7",
      city: "24",
      area: "Kaushambi",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "bd7a399cdd86fabb33d97c5e04730622",
      cuisines: ["Snacks", "North Indian", "Chinese", "Fast Food", "Desserts"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 31,
      minDeliveryTime: 31,
      maxDeliveryTime: 31,
      slaString: "31 MINS",
      lastMileTravel: 3,
      slugs: {
        restaurant: "24seven-kaushambi-kaushambi",
        city: "noida",
      },
      cityState: "24",
      address:
        "Sector-5, Vaishali, Ghaziabad-201010, , Ghaziabad Nagar Nigam Zone-5, Ghaziabad, Uttar Pradesh-201010",
      locality: "Sector 5",
      parentId: 3773,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 4300,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 4300,
        message: "",
        title: "Delivery Charge",
        amount: "4300",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7067564~p=4~eid=00000188-fbc1-5bd6-14c5-66e500980406~srvts=1687850933206",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "718086",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "--",
      totalRatings: 0,
      new: true,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "390170",
      name: "NH1 Bowls - Highway To North",
      uuid: "f30e9ca2-a715-44e7-9ff6-1b5dc4a1687a",
      city: "10459",
      area: "Ghaziabad",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "eodif0mxvnbgu4lnvvso",
      cuisines: ["North Indian", "Punjabi", "Home Food"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 18,
      minDeliveryTime: 13,
      maxDeliveryTime: 23,
      slaString: "13-23 MINS",
      lastMileTravel: 1.899999976158142,
      slugs: {
        restaurant: "nh1-bowls-highway-to-north-gyan-khand-ii-indirapuram",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "PLOT NO. CS-3, Upper Ground Back Side, C.S-4, Sucheta Kriplani Marg, U.G.F, Gyan Khand II, Indirapuram, Ghaziabad, Uttar Pradesh 201014",
      locality: "Indirapuram",
      parentId: 22452,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "390170",
        deliveryTime: 18,
        minDeliveryTime: 13,
        maxDeliveryTime: 23,
        lastMileTravel: 1.899999976158142,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "433576",
      name: "Ghee and Turmeric",
      uuid: "8947d91e-edc1-4e07-9eec-98f8b959ddbe",
      city: "10459",
      area: "Ghaziabad",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "d6jm9eixskxl8orksbfb",
      cuisines: ["North Indian", "Tandoor", "Punjabi"],
      tags: [],
      costForTwo: 50000,
      costForTwoString: "₹500 FOR TWO",
      deliveryTime: 19,
      minDeliveryTime: 19,
      maxDeliveryTime: 19,
      slaString: "19 MINS",
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: "ghee-and-turmeric-indirapuram-ck-ghaziabad-indirapuram",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "Unit No 2,1st Floor, One Square 68/1,  Shakti Khand 3, Indirapuram,  Ghaziabad, Uttar Pradesh 201010.",
      locality: "Indirapuram",
      parentId: 261287,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "433576",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.9",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "617768",
      name: "Taco Bell",
      uuid: "86f460e1-67a2-4846-892f-dc68599b2adc",
      city: "10459",
      area: "Sector 63",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "e7f40335a66b230f5eda766022dfecbd",
      cuisines: ["Mexican"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: "35 MINS",
      lastMileTravel: 4.599999904632568,
      slugs: {
        restaurant: "taco-bell-noida-sec-63-sector-64",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "H-1A/035, GROUND FLOOR, SECTOR - 63NOIDA CITY ZONE-1, Gautam Buddha Nagar, Uttar Pradesh-201301",
      locality: "H Block",
      parentId: 1557,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 4300,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 4300,
        message: "",
        title: "Delivery Charge",
        amount: "4300",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=6999829~p=7~eid=00000188-fbc1-5bd6-14c5-66e600980747~srvts=1687850933206",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "4.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        subHeader: "UPTO ₹80",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "617768",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 4.599999904632568,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.8",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "629572",
      name: "White Hart Pizza",
      uuid: "77a7b952-c37a-4eb1-a040-007d8cee71dc",
      city: "10459",
      area: "Indirapuram",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "mznveqfmric44rydj4ie",
      cuisines: ["Pizzas", "Burgers"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 19,
      minDeliveryTime: 19,
      maxDeliveryTime: 19,
      slaString: "19 MINS",
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant: "white-hart-pizza-indirapuram-indirapuram",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "Plot No-401 ,Near peepal chowk ,Niti  Khand-3 ,indirapuram , Makanpur,  Indirapuram, Ghaziabad Nagar Nigam  Zone-6, Ghaziabad, Uttar Pradesh - 201014",
      locality: "Niti Khand-3",
      parentId: 225871,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "629572",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "450053",
      name: "Thakur Sahab",
      uuid: "9dbdb542-9942-4590-ba90-f41f40eadf4f",
      city: "10459",
      area: "Indirapuram",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "vnskbrdneh3jmptj6n0w",
      cuisines: ["Chinese", "North Indian", "Indian"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 19,
      minDeliveryTime: 19,
      maxDeliveryTime: 19,
      slaString: "19 MINS",
      lastMileTravel: 0.4000000059604645,
      slugs: {
        restaurant: "thakur-sahab-da-dhaba-indirapuram-indirapuram",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "F-4, Plot No. 345, Shakti Khand-3, Indirapuram, Makanpur, Indirapuram, Ghaziabad Nagar Nigam Zone-6, Ghaziabad, Uttar Pradesh - 201014",
      locality: "Indirapuram",
      parentId: 270736,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.4 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "450053",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        lastMileTravel: 0.4000000059604645,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 20,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "49199",
      name: "The Punjabi Junction",
      uuid: "f8528b05-656e-43ea-95be-6418528b04e3",
      city: "10459",
      area: "Indirapuram",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "xmmqtwxqpvy4xhc3gqzl",
      cuisines: ["North Indian", "Mughlai"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 23,
      minDeliveryTime: 23,
      maxDeliveryTime: 23,
      slaString: "23 MINS",
      lastMileTravel: 1.399999976158142,
      slugs: {
        restaurant: "the-punjabi-junction-indirapuram-indirapuram",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "SE- 45 , Basement , opposite Niti Khand 3 Gate no 1 , plot no 12 ( A) , adjustment to Flavours of Chakhna restaurant  Jaipuria Sunrise Plaza , Indirapuram- 201014 ( Ahinsa Khand )",
      locality: "Jaipuria Sunrise Green",
      parentId: 13471,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7177993~p=10~eid=00000188-fbc1-5bd6-14c5-66e700980a49~srvts=1687850933206",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.3 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "49199",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        lastMileTravel: 1.399999976158142,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.0",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "239262",
      name: "Ministry Of Foods",
      uuid: "6d8a8f59-d1ee-4069-a9ad-c91879f68fea",
      city: "10459",
      area: "Ghaziabad",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "idzbahgo3fmlwxh1ffxe",
      cuisines: ["Indian"],
      tags: [],
      costForTwo: 50000,
      costForTwoString: "₹500 FOR TWO",
      deliveryTime: 19,
      minDeliveryTime: 19,
      maxDeliveryTime: 19,
      slaString: "19 MINS",
      lastMileTravel: 0.4000000059604645,
      slugs: {
        restaurant: "ministry-of-foods-sahibabad-sahibabad",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "F-4, Plot No. 345, Shakti Khand-3, Indirapuram, Makanpur, Indirapuram, Ghaziabad Nagar Nigam Zone-6, Ghaziabad, Uttar Pradesh - 201014",
      locality: "Indirapuram",
      parentId: 136566,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.4 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "239262",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        lastMileTravel: 0.4000000059604645,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "487025",
      name: "Annapurna Bhojanalya",
      uuid: "28550b84-d6d3-4510-84ce-061361d21952",
      city: "10459",
      area: "Ghaziabad",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "f8jxvbyyy7bbiyaemdem",
      cuisines: ["Indian"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 19,
      minDeliveryTime: 19,
      maxDeliveryTime: 19,
      slaString: "19 MINS",
      lastMileTravel: 0.4000000059604645,
      slugs: {
        restaurant: "annapurna-bhojnalya-indirapuram-indirapuram-3",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "Shop no 26 First Floor Nipun Wonder Mall  Shakti Khand 2 Indirapuram , Makanpur,  Indirapuram , Ghaziabad Nagar Nigam  Zone-6, Ghaziabad, Uttar Pradesh-201014",
      locality: "Indirapuram",
      parentId: 34010,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.4 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "487025",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        lastMileTravel: 0.4000000059604645,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.8",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "429000",
      name: "Imperfecto",
      uuid: "0ff458bd-07d6-4b59-9f79-e17eebb13295",
      city: "10459",
      area: "Ghaziabad",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "pgstpaxj9c8wdxdvuz7t",
      cuisines: ["North Indian", "Biryani", "Chinese", "Italian"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 23,
      minDeliveryTime: 23,
      maxDeliveryTime: 23,
      slaString: "23 MINS",
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: "imperfecto-indirapuram-indirapuram",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "Plot No 16, Indirapuram Habitat Centre, Ahinsa Khand 1, Indirapuram,Ghaziabad, Uttar Pradesh 201014",
      locality: "Indirapuram",
      parentId: 239216,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7031573~p=13~eid=00000188-fbc1-5bd6-14c5-66e800980d72~srvts=1687850933206",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.2 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "429000",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.9",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "152835",
      name: "Fusion Parantha",
      uuid: "362bb89c-d7b2-470b-83a7-bd48ec1500a3",
      city: "10459",
      area: "Ghaziabad",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "02731f6bd73f982bc74a522edd9c1b01",
      cuisines: ["North Indian"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 19,
      minDeliveryTime: 19,
      maxDeliveryTime: 19,
      slaString: "19 MINS",
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: "fusion-parantha-indirapuram",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "Plot no 211, Ground Floor 2, Niti khand 1, Indirapuram,Ghaziabad, Ghaziabad Nagar Nigam Zone-6, Ghaziabad (UttarPradesh), - 201010",
      locality: "Indirapuram",
      parentId: 85343,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "152835",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.6",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "83595",
      name: "Chinese Mania",
      uuid: "867cee2e-d4bf-4387-95a4-d27ac654f5fe",
      city: "10459",
      area: "Ghaziabad",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "v5rwt3c8linlgh6ejess",
      cuisines: ["Chinese"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 19,
      minDeliveryTime: 19,
      maxDeliveryTime: 19,
      slaString: "19 MINS",
      lastMileTravel: 0.4000000059604645,
      slugs: {
        restaurant: "chinese-mania-ahinsa-khand-2-sector-64",
        city: "noida-1",
      },
      cityState: "10459",
      address:
        "2nd Floor, Nipun Wonder Mall, Shakti Khand 2, Indirapuram, Ghaziabad",
      locality: "Indirapuram",
      parentId: 13268,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.4 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "83595",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        lastMileTravel: 0.4000000059604645,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
];

export default resObj;
